@apiURL={{$dotenv API_URL}}
@authToken={{$dotenv TEMP_TOKEN}}

### Hämta alla produkter (Require Auth)
GET {{apiURL}}products
Authorization: Bearer {{authToken}}

### Hämta en specifik produkt (Require Auth)
GET {{apiURL}}products/785-GFI
Authorization: Bearer {{authToken}}

### Lägg till en ny produkt (Require Auth)
POST {{apiURL}}products
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "country": "Spanien",
    "category": "Ale",
    "name": "San Miguel Selecta 2",
    "price": 2.99,
    "description": "Frisk och maltig lager är ett balanserat och lättdrucket, underjäst öl.",
    "image": "path-to-image"
}

### Uppdatera en produkt (Require Auth)
PUT {{apiURL}}products/785-GFI
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Pale Ale Special Edition",
    "price": 69.99
}

### Ta bort en produkt (Require Auth)
DELETE {{apiURL}}products/345-ESL
Authorization: Bearer {{authToken}}