@apiURL={{$dotenv API_URL}}
@authToken={{$dotenv TEMP_TOKEN}}

### Hämta alla produkter
GET {{apiURL}}products

### Hämta en specifik produkt
GET {{apiURL}}products/10000-FIL

### Lägg till en ny produkt (Require Auth)
POST {{apiURL}}products
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "country": "Finland",
    "category": "Lager",
    "name": "Lapin Kulta",
    "price": 1,
    "description": "Ugh.",
    "image": "path-to-image"
}

### Uppdatera en produkt (Require Auth)
PUT {{apiURL}}products/10000-FIL
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Pale Ale Special Edition",
    "price": 69.99
}

### Ta bort en produkt (Require Auth)
DELETE {{apiURL}}products/10000-MXL
Authorization: Bearer {{authToken}}

###

POST {{apiURL}}products/batch
Content-Type: application/json

{
    "product_codes": ["10000-FIL", "10000-IES"]
}